### ISSUE TITLE
missed image files

### ISSUE THREAD

**Issue by liouxiao** [mandoku/mandoku#24]
There's no folder `/doc/images`, and some image files are not found when opening "mandoku-install-en.org". Here's list of the broken urls -

https://github.com/mandoku/mandoku/blob/master/doc/images/emacs-splash.png

https://github.com/mandoku/mandoku/raw/master/doc/images/mandoku-catalog-txt.png

https://github.com/mandoku/mandoku/blob/master/doc/images/mandoku-index-1.png

https://github.com/mandoku/mandoku/blob/master/doc/images/mandoku-title-search-1.png

**Comment by cwittern** [comment]
Hi,

Thanks for letting me know! The problem should be fixed now.
Chris

Christian Wittern, Kyoto

**Comment by liouxiao** [comment]
Thanks!
